version: '3'

services:
  mariadb:
    env_file:
    - path: ./.env
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./mariadb/datadir:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3307:3306"

  phpmyadmin:
    env_file:
    - path: ./.env
    image: phpmyadmin
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
    restart: always
    ports:
      - "8070:80"
    networks:
      - backend
      
  my-api:
    image: api_project_system
    depends_on:
      mariadb:
        condition: service_started
    restart:
      always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./API_project_system/API_project_system/bin/Debug/net8.0:/app
    networks:
      - backend
      
networks:
  backend:
